### ISSUE TITLE
Export `Pojo` types.

### ISSUE THREAD

**Issue by yfwz100** [tskj/typescript-json-decoder#1]
At present, if I want to reference the `Pojo` type, I have to write

```ts
import { Pojo } from "typescript-json-decoder/dist/pojo";
```

which is not convenient and seems like the types are private.

**Comment by tskj** [comment]
Ah I hadn't thought about this - what's your usecase for wanting to reference the type? I'm mostly just curious, I will make a release exposing it anyway.

**Comment by yfwz100** [comment]
If someone write custom decoder in typescript, the parameter should be explicitly typed.

e.g.

```ts
const specialType = (v: Pojo) => AnotherType;
const myDecoder = record({
    username: specialType,
});
```

**Comment by tskj** [comment]
Of course! Thanks for raising the issue.
