### ISSUE TITLE
Unable to decode string union

### ISSUE THREAD

**Issue by Bjorn-Strom** [tskj/typescript-json-decoder#10]
Hi and thank you for making such a great library.

I am having a slight issue decoding a union of literals.
Where I am getting a strange error on the following code
```typescript
const fruitDecoder = record({
  amount: number,
  type: union("Apple" | "Orange"),
  type2: union(literal("Apple") | literal("orange"))
});
```
`The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.ts(2362)
Argument of type 'number' is not assignable to parameter of type 'Decoder<unknown>'.ts(2345)`

I made a small code-sandbox example reproducing the problem:
https://codesandbox.io/s/competent-grass-nib0k?file=/src/index.ts

**Comment by tskj** [comment]
Thanks for writing up a repro!

So the issue I think is confusing type level expressions and regular runtime expressions. The function `union` expects two runtime strings, which the Typescript type system uses to infer the decoded type of `union("Apple", "Orange")`. So it's simply a matter of substituting pipes (`|`) for commas (`,`). The correct expression then is:

```typescript
const fruitDecoder = record({
  amount: number,
  type: union("Apple", "Orange"),
  type2: union(literal("Apple"), literal("orange"))
});
```

I also mended the sandbox to illustrate: https://codesandbox.io/s/async-cloud-r734i

**Comment by Bjorn-Strom** [comment]
I see!
Thanks for the help and the quick reply! 👍
