### ISSUE TITLE
Add automated test suite?

### ISSUE THREAD

**Issue by zoul** [tskj/typescript-json-decoder#5]
Splitting the discussion from #4 to keep things tidy – would it be possible to add an automated test suite? It would be nice to be able to run `npm test` after making some changes to make sure nothing was broken.

Is the main problem testing the type inference? If yes, would something like [tsd](https://github.com/SamVerschueren/tsd) work? It can do things like this:

```typescript
import {expectType} from 'tsd';
import concat from '.';

expectType<string>(concat('foo', 'bar'));
expectType<string>(concat(1, 2));
```

**Comment by tskj** [comment]
A fully automated test suite is a great next step for this library! While testing that runtime values and behaviour is corrent can't hurt and is important as well, testing that types are inferred correctly has been the blocker for not getting it done before.

I didn't know a library like this existed, this looks very promising!
