### ISSUE TITLE
A union decoder combined with string decoder

### ISSUE THREAD

**Issue by Addeuz** [tskj/typescript-json-decoder#8]
Hello, we are trying to implement decoders for our endpoints that talks to a rust backend. I was able to create a small endpoint and with some custom decoders successfully. But now I am stuck at our login endpoint. It gives us a token and a user key that was a discriminated union before trying to implement decoders (it will still be after turning implementing a decoder).

This is my response from the backend:
```json
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDE4MjY5NjEsImlkIjp7InR5cGUiOiJVc2VyIiwiaWQiOiJhYzAwMDAwMi0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEifSwicm9sZXMiOlt7InJvbGUiOiJBY2NvdW50YW50IiwiaWQiOiJlMTAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEifV19.5QmjihSDjT6kaNnSsPKMmsoDhUmEQc3I0Q8l8eZjoFI",
    "user": {
        "type": "User",
        "account": {
            "id": "ac000002-0000-0000-0000-000000000001",
            "name": {
                "first": "Andreas",
                "last": "Johansson"
            },
            "email": "andreas.johanson@furlands.se"
        },
        "roles": [
            {
                "type": "Accountant",
                "employer": {
                    "id": "e1000000-0000-0000-0000-000000000001",
                    "corporateId": "556195-3463",
                    "companyName": "Furlands Revisionsbyrå Aktiebolag"
                }
            }
        ]
    }
}
```

And this is the highest decoder:
```js
record({
    token: string,
    user: personDecoder
})
```

This is the `personDecoder` and subsequently `userDecoder` and `guestDecoder`:
```js
export const personDecoder = union(userDecoder, guestDecoder);

export const userDecoder = record({
  type: decode('User'),
  token: string,
  account: {
    id: string,
    name: nameDecoder,
    email: string
  },
  roles: rolesDecoder,
  intent: optional(union('Accountant', 'Company'))
});

const guestDecoder = record({
  type: decode('Guest'),
  email: string,
  employer: optional({
    id: string,
    corporateId: corporateIdDecoder,
    companyName: string
  }),
  reference: union(
    {
      ref: decode('SsoMicrosoft'),
      tid: string,
      oid: string
    },
    {
      ref: decode('SsoMicrosoftPersonal'),
      oid: string
    }
  )
});
```

Also here is the `rolesDecoder`. However I don't think this one is the issue since I get the error earlier:
```js
export const rolesDecoder = array(
  union(
    {
      type: decode('Accountant'),
      employer: {
        id: string,
        corporateId: corporateIdDecoder,
        companyName: string
      }
    },
    {
      type: decode('Employer'),
      employer: {
        id: string,
        corporateId: corporateIdDecoder,
        companyName: string
      }
    },
    {
      type: decode('Company'),
      corporateId: corporateIdDecoder,
      companyName: string
    }
  )
);
```

So when I'm trying to decode the object returned I get this error:
```
The value `undefined` is not of type `string`, but is of type `undefined`
when trying to decode the key `token` in `{"type":"User","account":{"id":"ac000002-0000-0000-0000-000000000001","name":{"first":"Andreas","last":"Johansson"},"email":"andreas.johanson@furlands.se"},"roles":[{"type":"Accountant","employer":{"id":"e1000000-0000-0000-0000-000000000001","corporateId":"556195-3463","companyName":"Furlands Revisionsbyrå Aktiebolag"}}]}`

The value `"User"` is not the literal `"Guest"`
when trying to decode the key `type` in `{"type":"User","account":{"id":"ac000002-0000-0000-0000-000000000001","name":{"first":"Andreas","last":"Johansson"},"email":"andreas.johanson@furlands.se"},"roles":[{"type":"Accountant","employer":{"id":"e1000000-0000-0000-0000-000000000001","corporateId":"556195-3463","companyName":"Furlands Revisionsbyrå Aktiebolag"}}]}`

Could not match any of the union cases
when trying to decode the key `user` in `{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDE4MjY5NjEsImlkIjp7InR5cGUiOiJVc2VyIiwiaWQiOiJhYzAwMDAwMi0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEifSwicm9sZXMiOlt7InJvbGUiOiJBY2NvdW50YW50IiwiaWQiOiJlMTAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEifV19.5QmjihSDjT6kaNnSsPKMmsoDhUmEQc3I0Q8l8eZjoFI","user":{"type":"User","account":{"id":"ac000002-0000-0000-0000-000000000001","name":{"first":"Andreas","last":"Johansson"},"email":"andreas.johanson@furlands.se"},"roles":[{"type":"Accountant","employer":{"id":"e1000000-0000-0000-0000-000000000001","corporateId":"556195-3463","companyName":"Furlands Revisionsbyrå Aktiebolag"}}]}}`
```

The first error I don't simply understand since I don't have any field called `token` in the `userDecoder`. It seems like the highest decoder checks for `token` in the `user` key instead of in the highest record...

The second error is also weird.. Since I assumed my implementation would turn my decoders into discriminated unions and that the fact that the type is "User" in my returned object would be fine and I would get the user object back..

The third issue also seems weird to me because as I see it my decoder for user match the data coming in so It should be able to match that union case?

If someone can help me that would be greatly appreciated since we decided to go with your decoder library because of the easy of use at first glance and usage..

**Comment by tskj** [comment]
Hi, thanks for using the library, and for creating such a detailed description of your issue! 

The first error I think is just a simple mistake in your user decoder - between `type` and `account` you have actually specified `token: string`, which as you say, is incorrect, because there is no token at that location in your data (which is why the decoder fails). Simply removing that line should fix that up.
![bilde](https://user-images.githubusercontent.com/25415972/148792541-6d0cba81-1021-4bf4-b891-fc671355fb9e.png)

The rest of the errors seem to follow from that. As soon as it manages to parse `User` properly, it should work. I have tested your code without the `token` decoder in the wrong spot, and it seems to work, but please get back to me if it doesn't!

Also, it's super cool that you are using discriminated unions like that! The type inference is kind of ugly, but I don't know if it's possible to get Typescript to produce better looking types. But it does work as one would expect. If you don't mind, I will use an anonymized version of your example code as a test case, to make sure it keeps working also in the future.

**Comment by Addeuz** [comment]
Well, this is embarrassing.
When I saw the first error I thought it would be something like that so I looked in the `userDecoder` but I COULD NOT SEE any `token` field. I guess I was staring my self blind 😆 

And yes the rest of the errors did follow from that mistake! So now it works

You could absolutely use this as a test case. That's the least I can do for you since you created this simple but yet so useful library!
